DROP TABLE QUEUES;
DROP SEQUENCE QUEUES_SEQ;

DROP TABLE ENGINEERS;
DROP SEQUENCE ENGINEERS_SEQ;

DROP TABLE CLIENTS;
DROP SEQUENCE CLIENTS_SEQ;

DROP TABLE VIEWS;
DROP SEQUENCE VIEWS_SEQ;

DROP TABLE PMRSTATUS;
DROP SEQUENCE PMRSTATUS_SEQ;